/**
 * Sealed prep: content/prep.ts never leaves your machine. `npm run prep:seal`
 * encrypts it into content/prep.sealed.json, which is safe to commit to a
 * public repo; the server decrypts it per request with PREP_SECRET.
 *
 * AES-256-GCM through Web Crypto, so the same code runs in Node (scripts,
 * `next start`) and on Cloudflare Workers. PREP_SECRET is 32 random bytes,
 * base64url, generated by `npm run prep:init`; there is no password to guess.
 */

export interface Sealed {
  v: 1;
  alg: "AES-256-GCM";
  /** base64url, 12 bytes */
  iv: string;
  /** base64url ciphertext with the GCM tag appended */
  data: string;
}

/** An empty placeholder: the audit has no prep sealed yet. */
export interface Unsealed {
  v: 0;
}

export type SealedFile = Sealed | Unsealed;

const AAD = new TextEncoder().encode("company-audit:prep:v1");

function toB64url(bytes: Uint8Array) {
  let s = "";
  for (let i = 0; i < bytes.length; i += 0x8000) s += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function fromB64url(s: string) {
  const bin = atob(s.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((s.length + 3) % 4));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function keyFrom(secret: string) {
  let raw: Uint8Array;
  try {
    raw = fromB64url(secret.trim());
  } catch {
    raw = new Uint8Array(0);
  }
  if (raw.length !== 32) throw new Error("PREP_SECRET must be 32 random bytes, base64url (run `npm run prep:init` to make one)");
  return crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["encrypt", "decrypt"]);
}

export function newSecret() {
  return toB64url(crypto.getRandomValues(new Uint8Array(32)));
}

export async function seal(plaintext: string, secret: string): Promise<Sealed> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const data = await crypto.subtle.encrypt({ name: "AES-GCM", iv, additionalData: AAD }, await keyFrom(secret), new TextEncoder().encode(plaintext));
  return { v: 1, alg: "AES-256-GCM", iv: toB64url(iv), data: toB64url(new Uint8Array(data)) };
}

/** Throws if the secret is wrong or the file was tampered with. */
export async function unseal(file: Sealed, secret: string): Promise<string> {
  const plain = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: fromB64url(file.iv), additionalData: AAD },
    await keyFrom(secret),
    fromB64url(file.data),
  );
  return new TextDecoder().decode(plain);
}

export function isSealed(file: unknown): file is Sealed {
  const f = file as Partial<Sealed> | null;
  return !!f && f.v === 1 && typeof f.iv === "string" && typeof f.data === "string";
}
